# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            R lunchs
tagline:          'Rencontres pluridisciplinaires autour de R à UniMail'
description:      'Rencontres pluridisciplinaires autour de R à UniMail'
url:              
baseurl:          /

author:
  name:           
  url:            

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:         

# Google services
google_analytics: UA-94119874-1
